### ISSUE TITLE
I followed the document steps, but the following error occurred.

### ISSUE THREAD

**Issue by monksoul** [alioguzhan/react-typescript-library#13]
![image](https://user-images.githubusercontent.com/22766122/137662909-cbe3b8d3-7409-4692-b3c9-81cebe9c49a7.png)

**Comment by alioguzhan** [comment]
Sorry for being late. I am not using Windows so I can't help you. But it looks like an error related to husky. Maybe you should consider checking the husky project's issues.

Thanks.
