### ISSUE TITLE
shelljs required on build

### ISSUE THREAD

**Issue by bastiion** [alioguzhan/react-typescript-library#18]
**Describe the bug**
shelljs is a requirement for husky to execute its checks

**To Reproduce**

after checking out the repository and
hitting `yarn` -> fails.

**Expected behavior**
build to run successfully without manually installing shelljs

**Log Output**

```
[5/5] Building fresh packages...
success Saved lockfile.
$ husky install
husky - Git hooks installed
Done in 20.01s.
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module './node_modules/shelljs/src/exec-child.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Environment (please complete the following information):**
 - OS: Linux, NixOS 22.05
 - Node version: v14.19.3

**Comment by alioguzhan** [comment]
Hi, thanks for reporting this. I will check it and back to you.

**Comment by alioguzhan** [comment]
I updated a few things and got rid of `shelljs`. I also added a `shell.nix` file. Can you please try it with the new branch:

```bash
git clone git@github.com:alioguzhan/react-typescript-library.git
git checkout alioguzhan/issue18
mv react-typescript-library test-library
cd test-library
yarn install
```

If it is working I will merge it.

**Comment by alioguzhan** [comment]
I tested it a few times. Seems working.
