### ISSUE TITLE
Future Request : Example App with typescript Template

### ISSUE THREAD

**Issue by MeetBhingradiya** [alioguzhan/react-typescript-library#26]
+ In ```tools/init.ts```  you can question it to user of this Repository.
+ Question : Would you like to TypeScript for Testing Library?
+ ANSWER : Boolean if yes install Typescript Template if no install JavaScript Template

### Additional

+ i hope you understand this Consept
+ If you don't understand comment here as 
I not understand to i will open pull request.

Thank You 
@MeetBhingradiya

**Comment by alioguzhan** [comment]
Hi, thanks for pointing this out. I will check what can be done and will let u know.

**Comment by MeetBhingradiya** [comment]
+ i looking for your permission : can i create a new template from this Repository ? @alioguzhan 

+ that contains multiple packages at a time with multiple testapps in one repository.

+ Automatically genrates packages and test react apps in JavaScript and TypeScript both Supported and can be useable with yarn and npm individual

+ I have full rodemap to creating template.

![Screenshot_20221213-065923_Replit.jpg](https://user-images.githubusercontent.com/102130001/207204784-796008e0-a30f-4569-afdd-053a2bd44bdf.jpg)

**Comment by alioguzhan** [comment]
hey, sure feel free to create a new one. ping me when it is done or if need any help! @MeetBhingradiya

**Comment by alioguzhan** [comment]
I am closing this for now. typescript support can be enabled by installing `typescript` and creating `tsconfig.json` file.
