### ISSUE TITLE
More than one copy of React in [Test App]

### ISSUE THREAD

**Issue by MeetBhingradiya** [alioguzhan/react-typescript-library#29]
**Describe the bug**
+ Actually this is not Bug but need to add in ```rollup.config.js```.

+ This is Link of [Stackoverflow](https://stackoverflow.com/questions/66488492/solve-having-more-than-one-copy-of-react-in-the-same-app)

+ **in  Second Answers** You see as Webpack he added external version of React so i don't know how to add in ```rollup.config.js```

+ This is Future Bug of this repo so that i informed through this Issue Report

**How I Discovered this Error in My TestApp and TestLibrary ?**
I am creating Powerful [Route Authorization Library](https://github.com/MeetBhingradiya/RouteLocker) that has Prevention from
+ Browsers
+ Devices
+ OS
+ AuthState
+ RoleState
+ Automatic Role by Role Redirect through after login [admin => /admin/dashboard , user => /home , vip => /home/vip ect.]
+ IP , Bots etc.<br/>
 This Library already i created and working fine in local file as part of every react app.
i need to clear one and only this error that i seen 3 months ago and still seeing.
i tryed every working library like react-router-dom, Muicore , 7+ teamplates but this repo has give me some confidence that i can transform it so please help me ! with ping heare<br/><br/>
Thanks for Read and give me your valuable time.

**Comment by alioguzhan** [comment]
Hey, `react`, `react-dom`, and the `library` should be `linked` to the library modules. Please see the below line:

https://github.com/alioguzhan/react-typescript-library/blob/main/tools/init.ts#L159

So, in your example app's `package.json`, there should be something like this:

```json
"my-library": "link:..",
"react": "link:../node_modules/react",
"react-dom": "link:../node_modules/react-dom",
```
With this, we shouldn't see that `multiple version of react` error. 

If you don't have it this way, you may use an old version of this template.

Can you please check your package.json check if this is the case?

**Comment by MeetBhingradiya** [comment]
Sorry i doesn't see same issue i opened that has same solution. i forgot about that i open this issue without seeing. 🤐
thankyou very much. Side Effects of tomuch coding😁

**Comment by MeetBhingradiya** [comment]
This Solution is Not Working See That Screenshots

#1 Main Export File of Library
![image](https://user-images.githubusercontent.com/102130001/222137538-f6d9a351-94f0-4b56-adbe-e5619f1268e8.png)
#2 Package Json File of Local Test App
![image](https://user-images.githubusercontent.com/102130001/222138117-3384e292-92f1-406d-9995-3720f8c3002b.png)
#3 App.js File on Local Test App 
![image](https://user-images.githubusercontent.com/102130001/222138642-2748f778-70b2-42b8-b7c5-2183df8135ce.png)
#4 Output
![image](https://user-images.githubusercontent.com/102130001/222138948-3b7e2e6c-908d-4aac-8afb-da14f460a756.png)

@alioguzhan

**Comment by MeetBhingradiya** [comment]
@alioguzhan

**Comment by alioguzhan** [comment]
Why are you importing another `React` as `React2`? This is expected since you have 2 Reacts now.

**Comment by MeetBhingradiya** [comment]
Debugging Testlibrary React and TestApp React is Same or not this give me not same.
As stackoverflow Answers.

**Comment by MeetBhingradiya** [comment]
Debugging Testlibrary React and TestApp React is Same or not this give me not same.
As stackoverflow Answers.

I tested Local and Published Library that has giving me same Error.


@alioguzhan 

I now trying to use your ```userscreen``` hook and resetting my present TestLibrary

**Comment by alioguzhan** [comment]
I am not sure how this template can help your situation since you are explicitly importing 2 different `React`. 

I don't see any use case for this, but if you believe there is try tweaking the rollup config or module system. 

I am closing this as `out of scope`.

**Comment by MeetBhingradiya** [comment]
I Got a Successfully working Library that's working fine.

Thanks @alioguzhan for Helping and Support ing to me

userscreen template worked for me.

**Comment by alioguzhan** [comment]
I am glad that you made it. 🚀
